SELECT * FROM USER_TABLES;

DROP TABLE MEMBER;

CREATE TABLE MEMBER(
	MPK INT PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	SCORE INT DEFAULT 0
);

INSERT INTO MEMBER VALUES((SELECT NVL(MAX(MPK),0)+1 FROM MEMBER),'홍길동',90);
INSERT INTO MEMBER VALUES((SELECT NVL(MAX(MPK),0)+1 FROM MEMBER),'임꺽정',100);


SELECT * FROM MEMBER;